// <auto-generated />
using System;
using FUMiniHotelManagement.DAO.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FUMiniHotelManagement.DAO.Migrations
{
    [DbContext(typeof(FUMiniHotelManagementContext))]
    [Migration("20241015073726_Change_Status_All")]
    partial class Change_Status_All
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.BookingDetail", b =>
                {
                    b.Property<Guid>("BookingReservationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookingReservationID");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoomID");

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("money");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("BookingReservationId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("BookingDetail", (string)null);
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.BookingReservation", b =>
                {
                    b.Property<Guid>("BookingReservationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookingReservationID");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerID");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("money");

                    b.HasKey("BookingReservationId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BookingReservation", (string)null);
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.RoomInformation", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoomID");

                    b.Property<string>("RoomDetailDescription")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int?>("RoomMaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("RoomPricePerDay")
                        .HasColumnType("money");

                    b.Property<string>("RoomStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoomTypeID");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("RoomInformation", (string)null);
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.RoomType", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoomTypeID");

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TypeNote")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomType", (string)null);
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__Customer__49A14740FDE69030")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.BookingDetail", b =>
                {
                    b.HasOne("FUMiniHotelManagement.BusinessObject.Entities.BookingReservation", "BookingReservation")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingDetail_BookingReservation");

                    b.HasOne("FUMiniHotelManagement.BusinessObject.Entities.RoomInformation", "Room")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingDetail_RoomInformation");

                    b.Navigation("BookingReservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.BookingReservation", b =>
                {
                    b.HasOne("FUMiniHotelManagement.BusinessObject.Entities.User", "Customer")
                        .WithMany("BookingReservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingReservation_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.RoomInformation", b =>
                {
                    b.HasOne("FUMiniHotelManagement.BusinessObject.Entities.RoomType", "RoomType")
                        .WithMany("RoomInformations")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoomInformation_RoomType");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.BookingReservation", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.RoomInformation", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.RoomType", b =>
                {
                    b.Navigation("RoomInformations");
                });

            modelBuilder.Entity("FUMiniHotelManagement.BusinessObject.Entities.User", b =>
                {
                    b.Navigation("BookingReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
